version: 2.1
orbs:
  gradle: circleci/gradle@3.0.0
  tcc: atomicjar/testcontainers-cloud-orb@0.1.0
workflows:
  build-and-test:
    jobs:
      - gradle/test:
          executor:
            tag: "17.0"
          pre-steps:
            - tcc/setup
