spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgresDialect
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
    enabled: true

logging.level:
  org.springframework:
    data: INFO
    jdbc.core.JdbcTemplate: DEBUG
